server:
  port: 8761 # 端口

spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中显示，默认显示 UNKNOWN


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka




#server:
#  port: 8761 # 端口
#
#spring:
#  profiles:
#    active: eureka6001
#  application:
#    name: eureka-server # 应用名称，会在Eureka中显示，默认显示 UNKNOWN
#
#---
#server:
#  port: 6001
#spring:
#  profiles: eureka6001
#eureka:
#  instance:
#    hostname: eureka6001.com
#  client:
#    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
#    fetch-registry: false # 是否拉取其它服务的信息，默认是true
#    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
#
#
#---
#server:
#  port: 6002
#spring:
#  profiles: eureka6002
#eureka:
#  instance:
#    hostname: eureka6002.com
#  client:
#    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
#    fetch-registry: false # 是否拉取其它服务的信息，默认是true
#    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
